// <auto-generated />
using System;
using ConfiguratorApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConfiguratorApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260609111427_SplitTShirts")]
    partial class SplitTShirts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConfiguratorApi.Models.MaterialLayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("DefaultColourHex")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("default_colour_hex");

                    b.Property<string>("DefaultColourName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("default_colour_name");

                    b.Property<string>("DefaultColourPantone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("default_colour_pantone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int")
                        .HasColumnName("display_order");

                    b.Property<string>("Gsm")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("gsm");

                    b.Property<string>("LayerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("layer_name");

                    b.Property<string>("MaterialName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("material_name");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("product_id");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("material_layers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("763b2b7f-4733-480b-9b15-445c7fe09587"),
                            DefaultColourHex = "",
                            DefaultColourName = "Default",
                            DefaultColourPantone = "",
                            DisplayOrder = 0,
                            Gsm = "220-230 GSM",
                            LayerName = "Body",
                            MaterialName = "Polyester Double Interlock (Sublimation)",
                            ProductId = new Guid("11111111-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("e3df1090-41f6-4d54-93dd-d1461d39e9f9"),
                            DefaultColourHex = "",
                            DefaultColourName = "Default",
                            DefaultColourPantone = "",
                            DisplayOrder = 1,
                            Gsm = "220-230 GSM",
                            LayerName = "Set Sleeve",
                            MaterialName = "Polyester Double Interlock (Sublimation)",
                            ProductId = new Guid("11111111-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("70b0f8f2-9ad2-4aa5-8a2d-059e2035c12f"),
                            DefaultColourHex = "",
                            DefaultColourName = "Default",
                            DefaultColourPantone = "",
                            DisplayOrder = 2,
                            Gsm = "220-230 GSM",
                            LayerName = "Collar",
                            MaterialName = "Polyester Double Interlock (Sublimation)",
                            ProductId = new Guid("11111111-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("b759283b-0bf4-4ab8-bacb-aa1000aac7d0"),
                            DefaultColourHex = "",
                            DefaultColourName = "Default",
                            DefaultColourPantone = "",
                            DisplayOrder = 3,
                            Gsm = "220-230 GSM",
                            LayerName = "Zapkam",
                            MaterialName = "Polyester Double Interlock (Sublimation)",
                            ProductId = new Guid("11111111-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("f7bf93df-3b11-4a7d-8766-037b4a2e1188"),
                            DefaultColourHex = "",
                            DefaultColourName = "Default",
                            DefaultColourPantone = "",
                            DisplayOrder = 4,
                            Gsm = "220-230 GSM",
                            LayerName = "Zk",
                            MaterialName = "Polyester Double Interlock (Sublimation)",
                            ProductId = new Guid("11111111-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("9bc9c855-d9a7-4f8e-a3b2-daf1d6db789b"),
                            DefaultColourHex = "",
                            DefaultColourName = "Default",
                            DefaultColourPantone = "",
                            DisplayOrder = 0,
                            Gsm = "220-230 GSM",
                            LayerName = "Body",
                            MaterialName = "Polyester Double Interlock (Sublimation)",
                            ProductId = new Guid("11111111-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("6d1e1c41-175f-47a6-8a64-1f6da62839ac"),
                            DefaultColourHex = "",
                            DefaultColourName = "Default",
                            DefaultColourPantone = "",
                            DisplayOrder = 1,
                            Gsm = "220-230 GSM",
                            LayerName = "Set Sleeve",
                            MaterialName = "Polyester Double Interlock (Sublimation)",
                            ProductId = new Guid("11111111-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("04c21c65-1833-4b82-85b1-5f466bd54add"),
                            DefaultColourHex = "",
                            DefaultColourName = "Default",
                            DefaultColourPantone = "",
                            DisplayOrder = 2,
                            Gsm = "220-230 GSM",
                            LayerName = "Collar",
                            MaterialName = "Polyester Double Interlock (Sublimation)",
                            ProductId = new Guid("11111111-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("aacf67d9-ee36-4de9-b9a2-5849fa7b6920"),
                            DefaultColourHex = "",
                            DefaultColourName = "Default",
                            DefaultColourPantone = "",
                            DisplayOrder = 3,
                            Gsm = "220-230 GSM",
                            LayerName = "Zapkam",
                            MaterialName = "Polyester Double Interlock (Sublimation)",
                            ProductId = new Guid("11111111-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("9c8d38fa-054f-44db-9156-6d9f549c0d30"),
                            DefaultColourHex = "",
                            DefaultColourName = "Default",
                            DefaultColourPantone = "",
                            DisplayOrder = 4,
                            Gsm = "220-230 GSM",
                            LayerName = "Zk",
                            MaterialName = "Polyester Double Interlock (Sublimation)",
                            ProductId = new Guid("11111111-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("46160f51-4261-4fd6-b119-b1ac700947fa"),
                            DefaultColourHex = "",
                            DefaultColourName = "Default",
                            DefaultColourPantone = "",
                            DisplayOrder = 0,
                            Gsm = "220-230 GSM",
                            LayerName = "Body",
                            MaterialName = "Polyester Double Interlock (Sublimation)",
                            ProductId = new Guid("11111111-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = new Guid("84ea2355-ec30-4883-a4ef-2db46602031c"),
                            DefaultColourHex = "",
                            DefaultColourName = "Default",
                            DefaultColourPantone = "",
                            DisplayOrder = 1,
                            Gsm = "220-230 GSM",
                            LayerName = "Collar",
                            MaterialName = "Polyester Double Interlock (Sublimation)",
                            ProductId = new Guid("11111111-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = new Guid("e4ef0bde-4767-47c2-b264-1801cff68cf6"),
                            DefaultColourHex = "",
                            DefaultColourName = "Default",
                            DefaultColourPantone = "",
                            DisplayOrder = 2,
                            Gsm = "220-230 GSM",
                            LayerName = "Zapkam",
                            MaterialName = "Polyester Double Interlock (Sublimation)",
                            ProductId = new Guid("11111111-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = new Guid("a69961eb-7860-4423-b4cf-594687d7f9f7"),
                            DefaultColourHex = "",
                            DefaultColourName = "Default",
                            DefaultColourPantone = "",
                            DisplayOrder = 3,
                            Gsm = "220-230 GSM",
                            LayerName = "Zk",
                            MaterialName = "Polyester Double Interlock (Sublimation)",
                            ProductId = new Guid("11111111-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = new Guid("58247031-eb66-4a11-b3d8-c824754d5403"),
                            DefaultColourHex = "",
                            DefaultColourName = "Default",
                            DefaultColourPantone = "",
                            DisplayOrder = 0,
                            Gsm = "220-230 GSM",
                            LayerName = "Bag",
                            MaterialName = "Polyester Double Interlock (Sublimation)",
                            ProductId = new Guid("11111111-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("37f1f16a-e03b-4138-a7a9-26ce8100da95"),
                            DefaultColourHex = "",
                            DefaultColourName = "Default",
                            DefaultColourPantone = "",
                            DisplayOrder = 1,
                            Gsm = "220-230 GSM",
                            LayerName = "Zip",
                            MaterialName = "Polyester Double Interlock (Sublimation)",
                            ProductId = new Guid("11111111-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("a451d880-8862-49ca-a326-c0443fd85087"),
                            DefaultColourHex = "",
                            DefaultColourName = "Default",
                            DefaultColourPantone = "",
                            DisplayOrder = 2,
                            Gsm = "220-230 GSM",
                            LayerName = "Handle",
                            MaterialName = "Polyester Double Interlock (Sublimation)",
                            ProductId = new Guid("11111111-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("086ac5df-9a39-43d9-9456-667fa97ebefc"),
                            DefaultColourHex = "",
                            DefaultColourName = "Default",
                            DefaultColourPantone = "",
                            DisplayOrder = 3,
                            Gsm = "220-230 GSM",
                            LayerName = "Piping",
                            MaterialName = "Polyester Double Interlock (Sublimation)",
                            ProductId = new Guid("11111111-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("ef7310a3-b8e4-468b-b52f-2bd99d682f68"),
                            DefaultColourHex = "",
                            DefaultColourName = "Default",
                            DefaultColourPantone = "",
                            DisplayOrder = 4,
                            Gsm = "220-230 GSM",
                            LayerName = "Mesh",
                            MaterialName = "Polyester Double Interlock (Sublimation)",
                            ProductId = new Guid("11111111-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("6f8f717f-0d5f-4973-8b3c-86a3ccdd98c0"),
                            DefaultColourHex = "#ffffff",
                            DefaultColourName = "Default",
                            DefaultColourPantone = "",
                            DisplayOrder = 0,
                            LayerName = "Back Color",
                            ProductId = new Guid("11111111-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("e7743c85-25e6-48c5-bbed-abb2b1443026"),
                            DefaultColourHex = "",
                            DefaultColourName = "Default",
                            DefaultColourPantone = "",
                            DisplayOrder = 1,
                            LayerName = "Camera Box",
                            ProductId = new Guid("11111111-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("8d2e6cad-13e9-40dd-9f89-0e7abe9a4aab"),
                            DefaultColourHex = "",
                            DefaultColourName = "Default",
                            DefaultColourPantone = "",
                            DisplayOrder = 0,
                            LayerName = "Body",
                            ProductId = new Guid("11111111-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("6fa75cfe-c2b4-408b-9de8-e93a793e434b"),
                            DefaultColourHex = "",
                            DefaultColourName = "Default",
                            DefaultColourPantone = "",
                            DisplayOrder = 1,
                            LayerName = "Detail",
                            ProductId = new Guid("11111111-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("a0063d2d-7241-4d11-aed2-05daefd99795"),
                            DefaultColourHex = "",
                            DefaultColourName = "Default",
                            DefaultColourPantone = "",
                            DisplayOrder = 2,
                            LayerName = "ZK Logo",
                            ProductId = new Guid("11111111-0000-0000-0000-000000000004")
                        });
                });

            modelBuilder.Entity("ConfiguratorApi.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("ProductLengthDesc")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("product_length_desc");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("product_name");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("product_type");

                    b.Property<string>("SleeveLength")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("sleeve_length");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("ProductType");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fully customizable polyester jersey with sublimation printing.",
                            IsActive = true,
                            ProductLengthDesc = "Sleeve Length",
                            ProductName = "Custom Jersey (Full Sleeves)",
                            ProductType = "tshirt",
                            SleeveLength = "Full Sleeves",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fully customizable polyester jersey with sublimation printing.",
                            IsActive = true,
                            ProductLengthDesc = "Sleeve Length",
                            ProductName = "Custom Jersey (Half Sleeves)",
                            ProductType = "tshirt",
                            SleeveLength = "Half Sleeves",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fully customizable polyester jersey with sublimation printing.",
                            IsActive = true,
                            ProductLengthDesc = "Sleeve Length",
                            ProductName = "Custom Jersey (Sleeveless)",
                            ProductType = "tshirt",
                            SleeveLength = "Sleeveless",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Customizable sports bag with multiple printable panels.",
                            IsActive = true,
                            ProductName = "Custom Bag",
                            ProductType = "bag",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Premium mobile case with pattern and color customization.",
                            IsActive = true,
                            ProductName = "Impact Cover Pro",
                            ProductType = "mobilecase",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Customizable sports shorts with body and detail layer coloring.",
                            IsActive = true,
                            ProductName = "Custom Shorts",
                            ProductType = "shorts",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("ConfiguratorApi.Models.SavedConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("config_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("product_id");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("saved_configurations");
                });

            modelBuilder.Entity("ConfiguratorApi.Models.MaterialLayer", b =>
                {
                    b.HasOne("ConfiguratorApi.Models.Product", "Product")
                        .WithMany("MaterialLayers")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ConfiguratorApi.Models.SavedConfiguration", b =>
                {
                    b.HasOne("ConfiguratorApi.Models.Product", "Product")
                        .WithMany("SavedConfigurations")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ConfiguratorApi.Models.Product", b =>
                {
                    b.Navigation("MaterialLayers");

                    b.Navigation("SavedConfigurations");
                });
#pragma warning restore 612, 618
        }
    }
}
