// <auto-generated />
using System;
using ConfiguratorApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConfiguratorApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260609100334_InitialSqlServerCreate")]
    partial class InitialSqlServerCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConfiguratorApi.Models.MaterialLayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("DefaultColourHex")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("default_colour_hex");

                    b.Property<string>("DefaultColourName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("default_colour_name");

                    b.Property<string>("DefaultColourPantone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("default_colour_pantone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int")
                        .HasColumnName("display_order");

                    b.Property<string>("Gsm")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("gsm");

                    b.Property<string>("LayerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("layer_name");

                    b.Property<string>("MaterialName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("material_name");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("product_id");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("material_layers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7ccb9ecc-3ebf-4bf1-aefc-2356796acfb9"),
                            DefaultColourHex = "",
                            DefaultColourName = "Default",
                            DefaultColourPantone = "",
                            DisplayOrder = 0,
                            Gsm = "220-230 GSM",
                            LayerName = "Body",
                            MaterialName = "Polyester Double Interlock (Sublimation)",
                            ProductId = new Guid("11111111-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("f0eb62be-81ac-4c2c-a7a3-654f59e88e25"),
                            DefaultColourHex = "",
                            DefaultColourName = "Default",
                            DefaultColourPantone = "",
                            DisplayOrder = 1,
                            Gsm = "220-230 GSM",
                            LayerName = "Set Sleeve",
                            MaterialName = "Polyester Double Interlock (Sublimation)",
                            ProductId = new Guid("11111111-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("3867d044-affa-4157-9e88-218231b38917"),
                            DefaultColourHex = "",
                            DefaultColourName = "Default",
                            DefaultColourPantone = "",
                            DisplayOrder = 2,
                            Gsm = "220-230 GSM",
                            LayerName = "Collar",
                            MaterialName = "Polyester Double Interlock (Sublimation)",
                            ProductId = new Guid("11111111-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("341cbe58-16ec-4924-98de-23bac5ea410c"),
                            DefaultColourHex = "",
                            DefaultColourName = "Default",
                            DefaultColourPantone = "",
                            DisplayOrder = 3,
                            Gsm = "220-230 GSM",
                            LayerName = "Zapkam",
                            MaterialName = "Polyester Double Interlock (Sublimation)",
                            ProductId = new Guid("11111111-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("8cf2eb8e-07c5-4837-b8dc-c891320c8c0e"),
                            DefaultColourHex = "",
                            DefaultColourName = "Default",
                            DefaultColourPantone = "",
                            DisplayOrder = 4,
                            Gsm = "220-230 GSM",
                            LayerName = "Zk",
                            MaterialName = "Polyester Double Interlock (Sublimation)",
                            ProductId = new Guid("11111111-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("04aa8224-04ea-4253-a1b2-602093b036a4"),
                            DefaultColourHex = "",
                            DefaultColourName = "Default",
                            DefaultColourPantone = "",
                            DisplayOrder = 0,
                            Gsm = "220-230 GSM",
                            LayerName = "Bag",
                            MaterialName = "Polyester Double Interlock (Sublimation)",
                            ProductId = new Guid("11111111-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("b1ea9d36-5625-497c-8cec-0556bb6ad1cd"),
                            DefaultColourHex = "",
                            DefaultColourName = "Default",
                            DefaultColourPantone = "",
                            DisplayOrder = 1,
                            Gsm = "220-230 GSM",
                            LayerName = "Zip",
                            MaterialName = "Polyester Double Interlock (Sublimation)",
                            ProductId = new Guid("11111111-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("fd3fb809-e2b5-4f28-bf58-a095b884e665"),
                            DefaultColourHex = "",
                            DefaultColourName = "Default",
                            DefaultColourPantone = "",
                            DisplayOrder = 2,
                            Gsm = "220-230 GSM",
                            LayerName = "Handle",
                            MaterialName = "Polyester Double Interlock (Sublimation)",
                            ProductId = new Guid("11111111-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("7fdec87d-c1e8-43ab-9fb7-1b6185a237ea"),
                            DefaultColourHex = "",
                            DefaultColourName = "Default",
                            DefaultColourPantone = "",
                            DisplayOrder = 3,
                            Gsm = "220-230 GSM",
                            LayerName = "Piping",
                            MaterialName = "Polyester Double Interlock (Sublimation)",
                            ProductId = new Guid("11111111-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("3d96ccd1-31c4-44d3-a0b0-18c14098c5e0"),
                            DefaultColourHex = "",
                            DefaultColourName = "Default",
                            DefaultColourPantone = "",
                            DisplayOrder = 4,
                            Gsm = "220-230 GSM",
                            LayerName = "Mesh",
                            MaterialName = "Polyester Double Interlock (Sublimation)",
                            ProductId = new Guid("11111111-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("9cd56b48-f00f-487d-8a18-4ddc780d16d1"),
                            DefaultColourHex = "#ffffff",
                            DefaultColourName = "Default",
                            DefaultColourPantone = "",
                            DisplayOrder = 0,
                            LayerName = "Back Color",
                            ProductId = new Guid("11111111-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("91b67656-0529-4957-bbf1-6a5de2cd9175"),
                            DefaultColourHex = "",
                            DefaultColourName = "Default",
                            DefaultColourPantone = "",
                            DisplayOrder = 1,
                            LayerName = "Camera Box",
                            ProductId = new Guid("11111111-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("f2e7a97c-0209-4fe3-992a-3e06e43a05e5"),
                            DefaultColourHex = "",
                            DefaultColourName = "Default",
                            DefaultColourPantone = "",
                            DisplayOrder = 0,
                            LayerName = "Body",
                            ProductId = new Guid("11111111-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("c0db4fed-e8a5-4704-9144-d4c4009daf58"),
                            DefaultColourHex = "",
                            DefaultColourName = "Default",
                            DefaultColourPantone = "",
                            DisplayOrder = 1,
                            LayerName = "Detail",
                            ProductId = new Guid("11111111-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("b081ded7-98cd-49f9-a9c8-e0a785e2b24c"),
                            DefaultColourHex = "",
                            DefaultColourName = "Default",
                            DefaultColourPantone = "",
                            DisplayOrder = 2,
                            LayerName = "ZK Logo",
                            ProductId = new Guid("11111111-0000-0000-0000-000000000004")
                        });
                });

            modelBuilder.Entity("ConfiguratorApi.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("ProductLengthDesc")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("product_length_desc");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("product_name");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("product_type");

                    b.Property<string>("SleeveLength")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("sleeve_length");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("ProductType");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fully customizable polyester jersey with sublimation printing.",
                            IsActive = true,
                            ProductLengthDesc = "Sleeve Length",
                            ProductName = "Custom Jersey",
                            ProductType = "tshirt",
                            SleeveLength = "Full Sleeves",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Customizable sports bag with multiple printable panels.",
                            IsActive = true,
                            ProductName = "Custom Bag",
                            ProductType = "bag",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Premium mobile case with pattern and color customization.",
                            IsActive = true,
                            ProductName = "Impact Cover Pro",
                            ProductType = "mobilecase",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Customizable sports shorts with body and detail layer coloring.",
                            IsActive = true,
                            ProductName = "Custom Shorts",
                            ProductType = "shorts",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("ConfiguratorApi.Models.SavedConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("config_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("product_id");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("saved_configurations");
                });

            modelBuilder.Entity("ConfiguratorApi.Models.MaterialLayer", b =>
                {
                    b.HasOne("ConfiguratorApi.Models.Product", "Product")
                        .WithMany("MaterialLayers")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ConfiguratorApi.Models.SavedConfiguration", b =>
                {
                    b.HasOne("ConfiguratorApi.Models.Product", "Product")
                        .WithMany("SavedConfigurations")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ConfiguratorApi.Models.Product", b =>
                {
                    b.Navigation("MaterialLayers");

                    b.Navigation("SavedConfigurations");
                });
#pragma warning restore 612, 618
        }
    }
}
